"use client";
import { useEffect, useState } from "react";
type User = { id?: string; email: string; role: string; leader_name?: string };
export function AdminRoleManager() {
  const [rows, setRows] = useState<User[]>([]), [email, setEmail] = useState(""), [role, setRole] = useState("admin"), [leader, setLeader] = useState(""), [message, setMessage] = useState("");
  const load = async () => { const r = await fetch("/api/ops-desk?type=users"); const x = await r.json(); setRows(x.items || []); };
  useEffect(() => { load(); }, []);
  const save = async () => { const r = await fetch("/api/ops-desk", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "role", email: email.trim().toLowerCase(), role, leaderName: leader.trim() }) }); const x = await r.json(); setMessage(r.ok && x.ok ? "Role berhasil dibuat" : x.error || "Gagal membuat role"); if (r.ok && x.ok) { setEmail(""); setLeader(""); load(); } };
  return <><div className="section-head"><div><div className="eyebrow">SECURITY · SUPER ADMIN</div><h1 className="headline">Role Administrasi</h1><div className="subtitle">Super admin mengatur akun admin lapangan untuk dashboard dan PWA.</div></div></div><div className="card" style={{ padding: 18, marginBottom: 16 }}><div className="card-title">Buat role baru</div><div className="form-grid"><label>Email pengguna<input value={email} onChange={e => setEmail(e.target.value)} placeholder="admin.divisi@jne.co.id" /></label><label>Role<select value={role} onChange={e => setRole(e.target.value)}><option value="admin">Admin lapangan</option><option value="leader">Leader</option><option value="pending">Pending</option></select></label><label>Nama leader/divisi<input value={leader} onChange={e => setLeader(e.target.value)} placeholder="Contoh: Admin Inbound" /></label></div><button className="primary" disabled={!email.trim()} onClick={save}>Simpan role</button>{message && <div className="toast" role="status">{message}</div>}</div><div className="card"><div className="card-head"><div className="card-title">Daftar role</div></div><div className="table-wrap"><table><thead><tr><th>Email</th><th>Role</th><th>Leader / Divisi</th></tr></thead><tbody>{rows.map(x => <tr key={x.id || x.email}><td>{x.email}</td><td><span className="pill">{x.role}</span></td><td>{x.leader_name || "—"}</td></tr>)}</tbody></table>{!rows.length && <div className="empty">Belum ada role tambahan.</div>}</div></div></>;
}
