"use client";
import { useEffect, useState } from "react";
import { Download, Upload, Search, X, RefreshCw, Pencil, LoaderCircle } from "lucide-react";
import { MASTER_FIELDS, MASTER_HEADERS, MasterRow } from "@/lib/courier-master";
import "./courier-master-admin.css";
const initialMonth=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date());
export function CourierMasterAdmin(){
  const [items,setItems]=useState<MasterRow[]>([]),[canManage,setCanManage]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[error,setError]=useState(""),[q,setQ]=useState(""),[month,setMonth]=useState(initialMonth);
  const [modal,setModal]=useState(false),[file,setFile]=useState<File|null>(null),[extra,setExtra]=useState(false),[preview,setPreview]=useState<any>(null),[decisions,setDecisions]=useState<Record<string,string>>({}),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[manual,setManual]=useState<MasterRow|null>(null),[limit,setLimit]=useState(100);
  const request=async(url:string,options?:RequestInit)=>{const r=await fetch(url,{...options,cache:"no-store"});const d=await r.json().catch(()=>({error:"Respons server tidak valid."}));if(!r.ok)throw new Error(d.error||"Permintaan gagal.");return d;};
  const load=async()=>{setLoading(true);setError("");try{const d=await request("/api/courier-master");setItems(d.items);setCanManage(d.can_manage);}catch(e){setError(e instanceof Error?e.message:"Gagal memuat data.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const open=()=>{setModal(true);setManual(null);setFile(null);setPreview(null);setDecisions({});setDirty(false);setError("");setLimit(100);};
  const inspect=async()=>{setBusy(true);setError("");try{
    let options:RequestInit;
    if(preview||manual){options={method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"preview",month,rows:preview?.rows??[{...manual,row:"Edit manual"}],decisions})};}
    else {const f=new FormData();f.append("file",file!);f.append("month",month);f.append("include_extra",String(extra));options={method:"POST",body:f};}
    const p=await request("/api/courier-master",options);setPreview(p);setDirty(false);
  }catch(e){setError(e instanceof Error?e.message:"Preview gagal.");}finally{setBusy(false);}};
  const commit=async()=>{if(busy||!preview||dirty||preview.counts.blocked)return;setBusy(true);setError("");try{
    const r=await request("/api/courier-master",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"commit",rows:preview.rows,month,decisions,review:preview.review})});
    setModal(false);setPreview(null);setNotice(`Sinkronisasi berhasil: ${r.counts.added} baru, ${r.counts.updated} diperbarui, ${r.counts.transitions} perubahan ID, ${r.counts.unchanged} tidak berubah.`);await load();
  }catch(e){setError(e instanceof Error?e.message:"Penyimpanan gagal.");}finally{setBusy(false);}};
  const download=async()=>{setBusy(true);setError("");try{const r=await fetch(`/api/courier-master?download=1&month=${month}`,{cache:"no-store"});if(!r.ok){const d=await r.json();throw new Error(d.error||"Unduhan gagal.");}const u=URL.createObjectURL(await r.blob()),a=document.createElement("a");a.href=u;a.download=`UPDATE_KURIR_${month}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){setError(e instanceof Error?e.message:"Unduhan gagal.");}finally{setBusy(false);}};
  const visible=items.filter(x=>[x.tgrid,x.name,x.leader,x.kanit,x.area,x.district].join(" ").toLowerCase().includes(q.toLowerCase()));
  const kind:Record<string,string>={added:"Baru",updated:"Berubah",unchanged:"Tidak berubah",transition:"Periksa ID",transitioned:"Ganti ID",blocked:"Bermasalah",duplicate:"Duplikat"};
  return <section className="courier-master-admin">
    <div className="section-head"><div><div className="eyebrow">DATA OPERASIONAL</div><h1 className="headline">Master kurir</h1><p className="subtitle">Identitas TGRID dan penempatan terbaru, tanpa duplikasi bulanan.</p></div><div className="actions"><button className="btn" disabled={busy||loading||!!error||!items.some(x=>x.active)} onClick={download}><Download size={16}/> Unduh Excel</button>{canManage&&<button className="primary" disabled={busy} onClick={open}><Upload size={16}/> Update massal</button>}</div></div>
    {notice&&<div className="cm-notice" role="status">{notice}</div>}{error&&!modal&&<div className="cm-error" role="alert">{error}<button className="btn" onClick={load}>Coba lagi</button></div>}
    <div className="cm-summary"><span><strong>{items.filter(x=>x.active).length}</strong> Personel aktif</span><span><strong>{items.filter(x=>x.active&&x.tgrid.startsWith("TGRFL")).length}</strong> Freelance</span><span><strong>{new Set(items.filter(x=>x.active&&x.area).map(x=>x.area)).size}</strong> Area</span></div>
    <div className="card"><div className="cm-toolbar"><label className="search"><Search size={16}/><input aria-label="Cari master kurir" placeholder="Cari nama, TGRID, leader, atau area…" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Periode label unduhan<input type="month" value={month} onChange={e=>{setMonth(e.target.value);setDirty(true);}}/></label><button className="icon-btn" onClick={load} disabled={loading} aria-label="Muat ulang"><RefreshCw size={16}/></button></div><p className="cm-hint">Unduhan berisi seluruh master aktif terbaru, bukan hanya hasil pencarian. Periode adalah label laporan, bukan snapshot historis.</p>
    <div className="table-wrap"><table><thead><tr>{["Personel / TGRID","Leader / Kanit","Shift / Kendaraan","Area / Kecamatan","Zone","Kode / KPI","Status",...(canManage?["Aksi"]:[])].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.slice(0,limit).map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.tgrid}</small></td><td>{x.leader||"—"}<small>{x.kanit||"—"}</small></td><td>{x.shift||"—"}<small>{x.vehicle||"—"}</small></td><td>{x.area||"—"}<small>{x.district||"—"}</small></td><td>{x.zone||"—"}</td><td>{x.code||"—"}<small>KPI {x.kpi||"—"}</small></td><td>{x.active?"Aktif":"Nonaktif"}</td>{canManage&&<td><button className="icon-btn" title="Edit penempatan" onClick={()=>{open();setManual({...x});}}><Pencil size={15}/></button></td>}</tr>)}</tbody></table></div>{loading?<div className="cm-empty">Memuat master kurir…</div>:!visible.length?<div className="cm-empty">Tidak ada data kurir yang cocok.</div>:visible.length>limit&&<button className="btn" onClick={()=>setLimit(limit+100)}>Tampilkan lebih banyak ({visible.length} data)</button>}</div>
    {modal&&<div className="modal-backdrop"><div className="cm-modal" role="dialog" aria-modal="true" aria-labelledby="cm-title"><div className="cm-modal-head"><div><h2 id="cm-title">{manual?"Edit penempatan kurir":"Update master kurir massal"}</h2><p>Periksa perubahan sebelum menyimpan. NIK login dan laporan lama tidak diubah.</p></div><button className="icon-btn" disabled={busy} onClick={()=>setModal(false)} aria-label="Tutup"><X/></button></div>
    {!preview&&<div className="cm-inputs"><label>Periode pembaruan<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{manual?<div className="cm-edit-grid">{MASTER_FIELDS.map((field,i)=><label key={field}>{MASTER_HEADERS[i]}<input readOnly={field==="tgrid"||field==="name"} value={manual[field]} onChange={e=>setManual({...manual,[field]:e.target.value})}/></label>)}</div>:<><label>Berkas update (.xlsx)<input type="file" accept=".xlsx" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label className="cm-checkbox"><input type="checkbox" checked={extra} onChange={e=>setExtra(e.target.checked)}/> Sertakan Sheet2 (tambahan freelance)</label><small>Sheet KURIR adalah sumber utama. Jika Sheet2 disertakan, TGRID ganda harus diselesaikan sebelum penyimpanan.</small></>}</div>}
    {preview&&<><div className="cm-preview-stats">{[["Baru",preview.counts.added],["Berubah",preview.counts.updated],["Ganti ID",preview.counts.transitions],["Tetap",preview.counts.unchanged],["Perlu diperiksa",preview.counts.blocked],["Baris berulang",preview.counts.duplicates]].map(([label,value])=><span key={label}><strong>{value}</strong>{label}</span>)}</div><div className="cm-preview-table"><table><thead><tr><th>Personel / Sumber</th><th>Hasil</th><th>Perubahan / Konfirmasi</th></tr></thead><tbody>{preview.entries.slice(0,limit).map((entry:any,index:number)=><tr key={index}><td><strong>{entry.name}</strong><small>{entry.tgrid} · {entry.row}</small></td><td><span className={`cm-badge ${entry.kind}`}>{kind[entry.kind]}</span></td><td>{entry.message&&<p>{entry.message}</p>}{entry.changes.map((c:any)=><div className="cm-change" key={c.field}>{MASTER_HEADERS[MASTER_FIELDS.indexOf(c.field)]}: <span>{c.before||"kosong"}</span> → <strong>{c.after||"kosong"}</strong></div>)}{entry.candidates.length>0&&<select aria-label={`Identitas ${entry.name}`} value={decisions[entry.tgrid]??""} onChange={e=>{setDecisions({...decisions,[entry.tgrid]:e.target.value});setDirty(true);}}><option value="">Pilih setelah memastikan identitas</option>{entry.candidates.map((c:any)=><option key={c.id} value={c.id}>Personel sama: {c.tgrid} · {c.name}{c.employee_nik?` · NIK ${c.employee_nik}`:""}</option>)}<option value="new">Personel berbeda — buat baru</option></select>}</td></tr>)}</tbody></table>{preview.entries.length>limit&&<button className="btn" onClick={()=>setLimit(limit+100)}>Tampilkan lebih banyak</button>}</div></>}
    {preview?.entries.some((entry:any)=>entry.identity_confirmation)&&<div className="cm-identity-checks"><h3>Periksa perbedaan nama</h3><p>Centang hanya setelah memastikan orangnya sama. Jika berbeda orang, perbaiki file dan jangan gabungkan identitas.</p>{preview.entries.filter((entry:any)=>entry.identity_confirmation).map((entry:any)=><label className="cm-checkbox" key={entry.tgrid}><input type="checkbox" checked={decisions[entry.tgrid]==="confirm-name"} onChange={e=>{setDecisions({...decisions,[entry.tgrid]:e.target.checked?"confirm-name":""});setDirty(true);}}/><span><strong>{entry.tgrid}</strong>{entry.identity_confirmation.nik?` · NIK ${entry.identity_confirmation.nik}`:""}: {entry.identity_confirmation.before} → {entry.identity_confirmation.after}</span></label>)}</div>}
    {error&&<div className="cm-error" role="alert">{error}</div>}<div className="cm-modal-actions">{preview&&<button className="btn" disabled={busy} onClick={()=>{setPreview(null);setDecisions({});}}>Pilih ulang data</button>}<button className="btn" disabled={busy||(!file&&!manual&&!preview)||!month} onClick={inspect}>{busy?<LoaderCircle size={16} className="cm-spin"/>:null}{dirty?"Periksa ulang perubahan":"Preview perubahan"}</button>{preview&&<button className="primary" disabled={busy||dirty||preview.counts.blocked>0} onClick={commit}>{busy?"Memproses…":"Konfirmasi & simpan"}</button>}</div></div></div>}
  </section>;
}
