"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, Crown, Search, Truck, Users, UserRound } from "lucide-react";
import { employeeStatus, employeeSummary, EMPLOYEE_STATUS_LABELS, EmployeeStatus } from "@/lib/employee-status";
import { employeeEmployment, EMPLOYMENT_LABELS, EmploymentType } from "@/lib/employee-employment";
import "./employee-status.css";
type Employee=Record<string,any>; type Segment="motor"|"mobil"|"staff"|"leader"|"coordinator";
const labels:Record<Segment,string>={motor:"Kurir Motor",mobil:"Kurir Mobil",staff:"Staf Operasional",leader:"Leader",coordinator:"Koordinator"};
function inSegment(x:Employee,s:Segment){const p=String(x.position||"");if(s==="motor")return/motor/i.test(p);if(s==="mobil")return/mobil/i.test(p);if(s==="leader")return/leader/i.test(p);if(s==="coordinator")return/coordinator/i.test(p);return !/motor|mobil|leader|coordinator/i.test(p)}
export function EmployeeDashboard(){
 const[employmentFilter,setEmploymentFilter]=useState<EmploymentType|"all">("all"),[visibleCount,setVisibleCount]=useState(25);
 const[rows,setRows]=useState<Employee[]>([]),[q,setQ]=useState(""),[statusFilter,setStatusFilter]=useState<"current"|"active"|"inactive"|"resigned">("active"),[selected,setSelected]=useState<Segment|null>(null),[selectedHub,setSelectedHub]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();const load=async()=>{try{const r=await fetch("/api/ops-desk?type=employees&view=summary",{cache:"no-store",signal:controller.signal}),data=await r.json();if(!r.ok||data.error)throw new Error("Data karyawan belum dapat dimuat.");if(!controller.signal.aborted){setRows(data.items||[]);setError("");}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Data karyawan belum dapat dimuat.");}finally{if(!controller.signal.aborted)setLoading(false);}};void load();const t=window.setInterval(()=>void load(),60000);return()=>{controller.abort();window.clearInterval(t)}},[]);
 const summary=employeeSummary(rows),activeRows=summary.active,inactiveRows=summary.inactive,resignedRows=summary.resigned,statusRows=statusFilter==="current"?summary.current:statusFilter==="active"?activeRows:statusFilter==="resigned"?resignedRows:inactiveRows,employmentRows=employmentFilter==="all"?statusRows:statusRows.filter(x=>employeeEmployment(x)===employmentFilter),scoped=selectedHub?employmentRows.filter(x=>String(x.hub||"").toUpperCase()===selectedHub):employmentRows,base=selected?scoped.filter(x=>inSegment(x,selected)):scoped,filtered=base.filter(x=>`${x.name} ${x.nik} ${x.position} ${x.hub} ${x.superior}`.toLowerCase().includes(q.toLowerCase()));
 const hubs=useMemo(()=>Object.entries(employmentRows.reduce((a:Record<string,number>,x)=>{const h=String(x.hub||"Tidak diketahui").toUpperCase();a[h]=(a[h]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[employmentRows]);
 useEffect(()=>setVisibleCount(25),[q,statusFilter,selected,selectedHub,employmentFilter]);
 const motor=scoped.filter(x=>inSegment(x,"motor")).length,mobil=scoped.filter(x=>inSegment(x,"mobil")).length,staff=scoped.filter(x=>inSegment(x,"staff")).length,leader=scoped.filter(x=>inSegment(x,"leader")).length,coordinator=scoped.filter(x=>inSegment(x,"coordinator")).length;
 const open=(s:Segment)=>{setSelected(s);setSelectedHub(null);setQ("")},openHub=(h:string)=>{setSelected(null);setSelectedHub(h);setQ("")};
 const statusButton=(v:EmployeeStatus,label:string,n:number)=><button aria-pressed={statusFilter===v} className={`status-summary ${statusFilter===v?"active":""}`} onClick={()=>{setStatusFilter(v);setSelected(null);setSelectedHub(null);setQ("")}}><span className={`status-dot ${v}`}>●</span>{label} <b>{loading||error?"—":n}</b></button>;
 const bars=[["motor",motor],["mobil",mobil],["staff",staff],["leader",leader],["coordinator",coordinator]] as [Segment,number][];
 return <><div className="section-head"><div><div className="eyebrow">OPERASIONAL · PERSONAL</div><h1 className="headline">{selectedHub?`Ringkasan Hub · ${selectedHub}`:selected?`Detail ${labels[selected]}`:"Ringkasan Karyawan"}</h1><div className="subtitle">Rekapitulasi data karyawan operasional dan struktur tim di lingkungan OPS LEGUTI.</div></div><div className="search top-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari karyawan, jabatan, atau hub..."/></div></div>
 <div className="employee-kpis"><button className="employee-kpi primary-kpi formation-kpi" onClick={()=>{setStatusFilter("current");setEmploymentFilter("all");setSelected(null);setSelectedHub(null);setQ("")}}><Users size={25}/><span>Total Formasi Karyawan<strong>{summary.formation}</strong><small className="formation-caption">Kuota operasional</small></span></button><button className={`employee-kpi segment-card ${selected==="motor"?"segment-active":""}`} onClick={()=>open("motor")}><Truck color="#d92d20" size={25}/><span>Kurir Motor<strong>{loading||error?"—":motor}</strong></span></button><button className={`employee-kpi segment-card ${selected==="mobil"?"segment-active":""}`} onClick={()=>open("mobil")}><Truck color="#1670c5" size={25}/><span>Kurir Mobil<strong>{loading||error?"—":mobil}</strong></span></button><button className={`employee-kpi segment-card ${selected==="staff"?"segment-active":""}`} onClick={()=>open("staff")}><UserRound color="#1670c5" size={25}/><span>Staf Operasional<strong>{loading||error?"—":staff}</strong></span></button></div>
 <div className="employee-summary-strip"><button onClick={()=>open("leader")}><Crown size={16}/> Leader <b>{loading||error?"—":leader}</b></button><button onClick={()=>open("coordinator")}><Users size={16}/> Koordinator <b>{loading||error?"—":coordinator}</b></button><button onClick={()=>openHub("SPC LEGUTI")}><Building2 size={16}/> SPC LEGUTI <b>{loading||error?"—":hubs.find(x=>x[0]==="SPC LEGUTI")?.[1]||0}</b></button><button onClick={()=>openHub("SP MALOKO")}><Building2 size={16}/> SP MALOKO <b>{loading||error?"—":hubs.find(x=>x[0]==="SP MALOKO")?.[1]||0}</b></button>{statusButton("active","Aktif",activeRows.length)}{statusButton("resigned","Resign / Belum Diganti",resignedRows.length)}{statusButton("inactive","Nonaktif",inactiveRows.length)}</div>
 <section className="employment-panel" aria-label="Jenis kepegawaian"><div className="employment-panel-heading"><span>Jenis Kepegawaian</span><small>{statusFilter==="active"?"Karyawan aktif":statusFilter==="inactive"?"Karyawan nonaktif":statusFilter==="resigned"?"Resign / belum diganti":"Posisi berjalan"} · pilih kategori untuk melihat daftar</small></div><div className="employment-filters">{(["all",...Object.keys(EMPLOYMENT_LABELS)] as ("all"|EmploymentType)[]).map(type=><button key={type} aria-pressed={employmentFilter===type} onClick={()=>setEmploymentFilter(type)}>{type==="all"?"Semua":EMPLOYMENT_LABELS[type]}<strong>{loading||error?"—":type==="all"?statusRows.length:statusRows.filter(x=>employeeEmployment(x)===type).length}</strong></button>)}</div></section>
 {!loading&&!error&&!selected&&!selectedHub&&<div className="employee-bi-grid"><div className="card bi-card"><div className="card-head"><div className="card-title">Jumlah Karyawan per Jabatan</div><span className="card-sub">Klik batang untuk melihat detail</span></div><div className="bar-chart">{bars.map(([key,value],i)=><button className="bar-row bar-row-button" key={key} onClick={()=>open(key)}><span>{labels[key]}</span><div><i style={{width:`${Math.min(100,Math.max(0,value/Math.max(1,...bars.map(([,count])=>count))*100))}%`,background:i===0?"#ef3340":i===1?"#1268bb":"#8aa0b7"}}/></div><b>{value}</b></button>)}</div></div><div className="card bi-card"><div className="card-head"><div className="card-title">Distribusi Karyawan per Hub</div></div><div className="hub-chart">{hubs.slice(0,4).map(([hub,value])=><div key={hub}><strong>{value}</strong><i style={{height:`${Math.max(16,Number(value)/Math.max(1,hubs[0]?.[1]||1)*130)}px`}}/><span>{hub}</span></div>)}</div></div></div>}
 <div className="card employee-table-card"><div className="card-head"><div><div className="card-title">{selectedHub?`Daftar Personel ${selectedHub}`:selected?`Daftar ${labels[selected]}`:statusFilter==="inactive"?"Daftar Karyawan Nonaktif — Sudah Diganti":statusFilter==="resigned"?"Daftar Resign — Belum Diganti":statusFilter==="current"?"Karyawan Aktif & Posisi Belum Diganti":"Daftar Karyawan Aktif"}</div><div className="card-sub">{employmentFilter==="all"?"Semua jenis kepegawaian":EMPLOYMENT_LABELS[employmentFilter]} · Kuota operasional {summary.formation}</div></div><span>{loading||error?"—":filtered.length} data</span></div>{(loading||error)&&<p role={error?"alert":"status"} className="employee-data-state">{error||"Memuat data karyawan…"}</p>}<div className="table-wrap"><table><thead><tr><th>Nama</th><th>NIK</th><th>Jabatan</th><th>Hub</th><th>Atasan</th><th>Kepegawaian</th><th>Status</th></tr></thead><tbody>{filtered.slice(0,visibleCount).map(x=><tr key={String(x.nik)}><td><strong>{x.name}</strong></td><td>{x.nik}</td><td>{x.position||"—"}</td><td>{x.hub||"—"}</td><td>{x.superior||"—"}</td><td><span className="employment-badge">{EMPLOYMENT_LABELS[employeeEmployment(x)]}</span></td><td><span className={`status-${employeeStatus(x)}`}>● {EMPLOYEE_STATUS_LABELS[employeeStatus(x)]}</span></td></tr>)}</tbody></table></div>{!loading&&!error&&filtered.length===0&&<p className="employee-data-state">Tidak ada karyawan pada filter ini.</p>}{!loading&&!error&&filtered.length>0&&<div className="employee-pagination"><span>Menampilkan {Math.min(visibleCount,filtered.length)} dari {filtered.length} karyawan</span>{visibleCount<filtered.length&&<button onClick={()=>setVisibleCount(count=>count+25)}>Tampilkan lebih banyak</button>}</div>}</div></>;
}
