"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, Crown, Search, Truck, Users, UserRound } from "lucide-react";
type Employee = Record<string, any>;
export function EmployeeDashboard() {
  const [rows, setRows] = useState<Employee[]>([]), [q, setQ] = useState("");
  useEffect(() => { fetch("/struktur update 2026_SEPT.xlsx").then(r => r.arrayBuffer()).then(async buffer => { const XLSX = await import("xlsx"); const wb = XLSX.read(buffer, { type: "array" }); const data = XLSX.utils.sheet_to_json<Employee>(wb.Sheets["LEGUTI MALOKO"] || wb.Sheets[wb.SheetNames[0]], { defval: "" }); setRows(data.map(x => ({ name: x["FULL NAME"] || "", position: x.POSITION || "", hub: x.HUB || "", superior: x["SUPERIOR 1"] || "", nik: x.NIK || x.NIA || "", active: true }))); }).catch(() => setRows([])); }, []);
  const filtered = rows.filter(x => `${x.name} ${x.position} ${x.hub}`.toLowerCase().includes(q.toLowerCase()));
  const motor = rows.filter(x => /motor/i.test(x.position || "")).length, mobil = rows.filter(x => /mobil/i.test(x.position || "")).length, staff = rows.filter(x => !/motor|mobil/i.test(x.position || "")).length;
  const hubs = useMemo(() => Object.entries(rows.reduce((a: Record<string, number>, x) => { const h = String(x.hub || "Tidak diketahui").toUpperCase(); a[h] = (a[h] || 0) + 1; return a; }, {})).sort((a,b) => b[1]-a[1]), [rows]);
  const positions = [["Kurir Motor", motor], ["Kurir Mobil", mobil], ["Staf Operasional", staff], ["Leader", rows.filter(x => /leader/i.test(x.position || "")).length], ["Koordinator", rows.filter(x => /coordinator/i.test(x.position || "")).length]];
  return <><div className="section-head"><div><div className="eyebrow">OPERASIONAL · PERSONAL</div><h1 className="headline">Ringkasan Karyawan</h1><div className="subtitle">Rekapitulasi data karyawan operasional dan struktur tim di lingkungan OPS LEGUT.</div></div><div className="search top-search"><Search size={16}/><input value={q} onChange={e => setQ(e.target.value)} placeholder="Cari karyawan, jabatan, atau hub..." /></div></div><div className="employee-kpis"><div className="employee-kpi primary-kpi"><Users size={25}/><span>Total Data Karyawan<strong>{rows.length}</strong></span></div><div className="employee-kpi"><Truck color="#d92d20" size={25}/><span>Kurir Motor<strong>{motor}</strong></span></div><div className="employee-kpi"><Truck color="#1670c5" size={25}/><span>Kurir Mobil<strong>{mobil}</strong></span></div><div className="employee-kpi"><UserRound color="#1670c5" size={25}/><span>Staf Operasional<strong>{staff}</strong></span></div></div><div className="employee-summary-strip"><span><Crown size={16}/> Leader <b>{positions[3][1]}</b></span><span><Users size={16}/> Koordinator <b>{positions[4][1]}</b></span><span><Building2 size={16}/> SPC LEGUTI <b>{hubs.find(x => x[0] === "SPC LEGUTI")?.[1] || 0}</b></span><span><Building2 size={16}/> SP MALOKO <b>{hubs.find(x => x[0] === "SP MALOKO")?.[1] || 0}</b></span></div><div className="employee-bi-grid"><div className="card bi-card"><div className="card-head"><div className="card-title">Jumlah Karyawan per Jabatan</div></div><div className="bar-chart">{positions.map(([label,value], i) => <div className="bar-row" key={String(label)}><span>{label}</span><div><i style={{width: `${Math.max(4, Number(value) / Math.max(1, motor) * 100)}%`, background: i === 0 ? "#ef3340" : i === 1 ? "#1268bb" : "#8aa0b7"}}/></div><b>{value}</b></div>)}</div></div><div className="card bi-card"><div className="card-head"><div className="card-title">Perbandingan Karyawan per Hub</div></div><div className="hub-chart">{hubs.slice(0,4).map(([hub,value]) => <div key={hub}><strong>{value}</strong><i style={{height: `${Math.max(16, Number(value) / Math.max(1, hubs[0]?.[1] || 1) * 130)}px`}}/><span>{hub}</span></div>)}</div></div></div><div className="card employee-table-card"><div className="card-head"><div className="card-title">Daftar Karyawan Terbaru</div><span>{filtered.length} data</span></div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Jabatan</th><th>Hub</th><th>Atasan</th><th>Status</th></tr></thead><tbody>{filtered.slice(0,10).map(x => <tr key={String(x.nik)}><td><strong>{x.name}</strong><small>{x.nik}</small></td><td>{x.position}</td><td>{x.hub}</td><td>{x.superior || "—"}</td><td><span className="status-active">● Aktif</span></td></tr>)}</tbody></table></div></div></>;
}
