"use client";
import { useEffect, useMemo, useState } from "react";
import { Download, Edit3, Plus, Search, Trash2, Upload, Users, X } from "lucide-react";
import * as XLSX from "xlsx";
type Employee = Record<string, any>;
const blank = { nik: "", name: "", position: "", dept: "", hub: "", level: "", superior: "", employment: "", start_date: "", active: true };
async function getEmployees(q = "") { try { const r = await fetch(`/api/ops-desk?type=employees&q=${encodeURIComponent(q)}`); return r.ok ? r.json() : { items: [] }; } catch { return { items: [] }; } }
export function EmployeeAdmin() {
  const [rows, setRows] = useState<Employee[]>([]), [q, setQ] = useState(""), [modal, setModal] = useState<"manual" | "bulk" | null>(null), [edit, setEdit] = useState<Employee>(blank), [bulk, setBulk] = useState(""), [notice, setNotice] = useState("");
  const load = async () => { const x = await getEmployees(q); if (x.items?.length) { setRows(x.items); return; } try { const response = await fetch("/struktur update 2026_SEPT.xlsx"); const workbook = XLSX.read(await response.arrayBuffer(), { type: "array" }); const sheet = workbook.Sheets["LEGUTI MALOKO"] || workbook.Sheets[workbook.SheetNames[0]]; const raw = XLSX.utils.sheet_to_json<Employee>(sheet, { defval: "" }); const imported = raw.map(row => ({ nik: String(row.NIK || row.NIA || ""), name: row["FULL NAME"] || "", position: row.POSITION || "", dept: row.DEPT || "", hub: row.HUB || "", level: row.LEVEL || "", superior: row["SUPERIOR 1"] || "", employment: row.STATUS || "", active: true })).filter(row => `${row.name} ${row.nik} ${row.position} ${row.hub}`.toLowerCase().includes(q.toLowerCase())); setRows(imported); } catch { setRows([]); } }; useEffect(() => { load(); }, [q]);
  const stats = useMemo(() => ({ total: rows.length, active: rows.filter(x => x.active !== false).length, motor: rows.filter(x => String(x.position).toLowerCase().includes("motor")).length, mobil: rows.filter(x => String(x.position).toLowerCase().includes("mobil")).length, staff: rows.filter(x => !/motor|mobil/i.test(x.position || "")).length }), [rows]);
  const save = async (body: Employee) => { const r = await fetch("/api/ops-desk", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setNotice(r.ok ? "Data karyawan diperbarui" : "Gagal menyimpan data"); setModal(null); setEdit(blank); load(); };
  const parseBulk = () => { const lines = bulk.trim().split(/\r?\n/).map(x => x.split("\t")); const heads = lines.shift()!.map(x => x.trim().toLowerCase()); return lines.filter(x => x[0]).map(x => Object.fromEntries(heads.map((h, i) => [({"full name":"name","superior 1":"superior","tgl masuk":"start_date","status":"active"} as any)[h] || h.replace(/\s+/g, "_"), x[i] || ""]))); };
  return <><div className="section-head"><div><div className="eyebrow">OPERASIONAL · TANGERANG SELATAN</div><h1 className="headline">Data karyawan</h1><div className="subtitle">Kelola struktur tim dan data personal operasional secara terpusat.</div></div><div className="actions"><button className="primary" onClick={() => { setEdit(blank); setModal("manual"); }}><Plus size={15}/> Tambah karyawan</button><button className="btn" onClick={() => setModal("bulk")}><Upload size={15}/> Tambah massal</button></div></div>
  <div className="employee-kpis"><div className="employee-kpi primary-kpi"><Users size={21}/><span>Total data karyawan</span><strong>{stats.total}</strong></div><div className="employee-kpi"><b>Kurir Motor</b><strong>{stats.motor}</strong></div><div className="employee-kpi"><b>Kurir Mobil</b><strong>{stats.mobil}</strong></div><div className="employee-kpi"><b>Staf operasional</b><strong>{stats.staff}</strong></div></div>
  <div className="card employee-table-card"><div className="employee-toolbar"><div className="search"><Search size={16}/><input value={q} onChange={e => setQ(e.target.value)} placeholder="Cari nama, NIK, jabatan, atau hub..." /></div><span>{stats.active} aktif dari {stats.total} data</span></div><div className="table-wrap"><table><thead><tr><th>Nama / NIK</th><th>Jabatan</th><th>Hub</th><th>Atasan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(x => <tr key={x.nik}><td><strong>{x.name}</strong><small>{x.nik}</small></td><td>{x.position || "—"}</td><td>{x.hub || "—"}</td><td>{x.superior || "—"}</td><td><span className={`pill ${x.active === false ? "closed" : "open"}`}>{x.active === false ? "Nonaktif" : "Aktif"}</span></td><td><button className="icon-btn" title="Edit" onClick={() => { setEdit({...x}); setModal("manual"); }}><Edit3 size={14}/></button><button className="icon-btn danger-icon" title="Hapus" onClick={() => { if (confirm(`Hapus ${x.name}?`)) save({ action: "deleteEmployee", nik: x.nik }); }}><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!rows.length && <div className="empty"><Users size={26}/><strong>Belum ada data karyawan</strong></div>}</div></div>
  {modal === "manual" && <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={() => setModal(null)}><X size={18}/></button><h2>{edit.nik ? "Edit karyawan" : "Tambah karyawan"}</h2>{[["NIK","nik"],["Nama lengkap","name"],["Jabatan","position"],["Departemen","dept"],["Hub","hub"],["Level","level"],["Atasan","superior"]].map(([label,key]) => <label key={key}>{label}<input value={edit[key] || ""} onChange={e => setEdit({...edit,[key]:e.target.value})} /></label>)}<label>Status<select value={edit.active === false ? "false" : "true"} onChange={e => setEdit({...edit,active:e.target.value === "true"})}><option value="true">Aktif</option><option value="false">Nonaktif</option></select></label><button className="primary full" disabled={!edit.nik || !edit.name} onClick={() => save({ action: edit.nik && rows.some(x => x.nik === edit.nik) ? "updateEmployee" : "employee", ...edit })}>Simpan</button></div></div>}
  {modal === "bulk" && <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={() => setModal(null)}><X size={18}/></button><h2>Tambah karyawan massal</h2><p className="card-sub">Tempel tabel Excel dengan header NIK, FULL NAME, POSITION, DEPT, HUB, LEVEL, SUPERIOR 1, STATUS.</p><textarea value={bulk} onChange={e => setBulk(e.target.value)} placeholder="NIK\tFULL NAME\tPOSITION\tDEPT\tHUB\n14010441\tNama\tKurir Motor Staff\tOperasional\tSPC LEGUTI" style={{ width: "100%", minHeight: 170, marginTop: 12 }}/><button className="primary full" disabled={!bulk.trim()} onClick={() => { const rows = parseBulk(); save({ action: "bulkEmployees", rows } as any); }}>Simpan data massal</button></div></div>}{notice && <div className="toast">{notice}</div>}</>;
}
