"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, Crown, Search, Truck, Users, UserRound } from "lucide-react";
type Employee = Record<string, any>; type Segment = "motor" | "mobil" | "staff" | "leader" | "coordinator";
const labels: Record<Segment,string> = { motor:"Kurir Motor", mobil:"Kurir Mobil", staff:"Staf Operasional", leader:"Leader", coordinator:"Koordinator" };
function inSegment(x: Employee, s: Segment) { const p=String(x.position||""); if(s==="motor") return /motor/i.test(p); if(s==="mobil") return /mobil/i.test(p); if(s==="leader") return /leader/i.test(p); if(s==="coordinator") return /coordinator/i.test(p); return !/motor|mobil|leader|coordinator/i.test(p); }
export function EmployeeDashboard() {
  const [rows,setRows]=useState<Employee[]>([]),[q,setQ]=useState(""),[statusFilter,setStatusFilter]=useState<"all"|"active"|"inactive">("active"),[selected,setSelected]=useState<Segment|null>(null),[selectedHub,setSelectedHub]=useState<string|null>(null);
  useEffect(()=>{const load=()=>fetch("/api/ops-desk?type=employees",{cache:"no-store"}).then(r=>r.json()).then(x=>setRows((x.items||[]).map((row:Employee)=>({...row,active:row.active!==false})))).catch(()=>setRows([]));load();const timer=window.setInterval(load,60000);return()=>window.clearInterval(timer)},[]);
  const activeRows=rows.filter(x=>x.active!==false),inactiveRows=rows.filter(x=>x.active===false),statusRows=statusFilter==="all"?rows:statusFilter==="active"?activeRows:inactiveRows,scopedRows=selectedHub?statusRows.filter(x=>String(x.hub||"").toUpperCase()===selectedHub):statusRows,base=selected?scopedRows.filter(x=>inSegment(x,selected)):scopedRows,filtered=base.filter(x=>`${x.name} ${x.nik} ${x.position} ${x.hub} ${x.superior}`.toLowerCase().includes(q.toLowerCase()));
  const hubs=useMemo(()=>Object.entries(statusRows.reduce((a:Record<string,number>,x)=>{const h=String(x.hub||"Tidak diketahui").toUpperCase();a[h]=(a[h]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[statusRows]);
  const motor=scopedRows.filter(x=>inSegment(x,"motor")).length,mobil=scopedRows.filter(x=>inSegment(x,"mobil")).length,staff=scopedRows.filter(x=>inSegment(x,"staff")).length,leader=scopedRows.filter(x=>inSegment(x,"leader")).length,coordinator=scopedRows.filter(x=>inSegment(x,"coordinator")).length;
  const open=(s:Segment)=>{setSelected(s);setSelectedHub(null);setQ("");window.scrollTo({top:0,behavior:"smooth"})},openHub=(h:string)=>{setSelected(null);setSelectedHub(h);setQ("");window.scrollTo({top:0,behavior:"smooth"})};
  const statusButton=(value:"active"|"inactive",label:string,count:number)=><button className={`status-summary ${statusFilter===value?"active":""}`} onClick={()=>{setStatusFilter(value);setSelected(null);setSelectedHub(null);setQ("")}}><span className={`status-dot ${value}`}>●</span>{label} <b>{count}</b></button>;
  return <><div className="section-head"><div><div className="eyebrow">OPERASIONAL · PERSONAL</div><h1 className="headline">{selectedHub?`Ringkasan Hub · ${selectedHub}`:selected?`Detail ${labels[selected]}`:"Ringkasan Karyawan"}</h1><div className="subtitle">Rekapitulasi data karyawan operasional dan struktur tim di lingkungan OPS LEGUTI.</div></div><div className="search top-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari karyawan, jabatan, atau hub..."/></div></div><div className="employee-kpis"><button className={`employee-kpi primary-kpi ${statusFilter==="all"?"segment-active":""}`} onClick={()=>setStatusFilter("all")}><Users size={25}/><span>Total Data Karyawan<strong>{rows.length}</strong></span></button><button className="employee-kpi segment-card" onClick={()=>open("motor")}><Truck color="#d92d20" size={25}/><span>Kurir Motor<strong>{motor}</strong></span></button><button className="employee-kpi segment-card" onClick={()=>open("mobil")}><Truck color="#1670c5" size={25}/><span>Kurir Mobil<strong>{mobil}</strong></span></button><button className="employee-kpi segment-card" onClick={()=>open("staff")}><UserRound color="#1670c5" size={25}/><span>Staf Operasional<strong>{staff}</strong></span></button></div><div className="employee-summary-strip"><button onClick={()=>open("leader")}><Crown size={16}/> Leader <b>{leader}</b></button><button onClick={()=>open("coordinator")}><Users size={16}/> Koordinator <b>{coordinator}</b></button><button className="hub-filter" onClick={()=>openHub("SPC LEGUTI")}><Building2 size={16}/> SPC LEGUTI <b>{hubs.find(x=>x[0]==="SPC LEGUTI")?.[1]||0}</b></button><button className="hub-filter" onClick={()=>openHub("SP MALOKO")}><Building2 size={16}/> SP MALOKO <b>{hubs.find(x=>x[0]==="SP MALOKO")?.[1]||0}</b></button>{statusButton("active","Aktif",activeRows.length)}{statusButton("inactive","Nonaktif",inactiveRows.length)}</div><div className="card employee-table-card"><div className="card-head"><div><div className="card-title">{selectedHub?`Daftar Personel ${selectedHub}`:selected?`Daftar ${labels[selected]}`:statusFilter==="inactive"?"Daftar Karyawan Nonaktif":"Daftar Karyawan Aktif"}</div><div className="card-sub">Klik status atau kategori untuk melihat detail nama karyawan</div></div><span>{filtered.length} data</span></div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>NIK</th><th>Jabatan</th><th>Hub</th><th>Atasan</th><th>Status</th></tr></thead><tbody>{filtered.slice(0,selected||selectedHub||statusFilter==="inactive"?100:10).map(x=><tr key={String(x.nik)}><td><strong>{x.name}</strong></td><td>{x.nik}</td><td>{x.position||"—"}</td><td>{x.hub||"—"}</td><td>{x.superior||"—"}</td><td><span className={x.active===false?"status-inactive":"status-active"}>● {x.active===false?"Nonaktif":"Aktif"}</span></td></tr>)}</tbody></table></div></div></>;
}
