"use client";
import { useEffect, useMemo, useState } from "react";
import { Bell, Boxes, Camera, ChevronRight, Grid2x2, Headphones, Home, Package, Search, UserRound } from "lucide-react";

const initial={type:"activation_user",userId:"",name:"",nik:"",department:"Inbound",location:"SPC LEGUTI",reason:"",shipmentNumbers:"",awb:"",category:"INVALID"};
type View="home"|"activity"|"problem"|"helpdesk"|"notifications"|"profile";
const greeting=()=>{const h=new Date().getHours();return h<11?"Selamat pagi":h<15?"Selamat siang":h<18?"Selamat sore":"Selamat malam"};
export function MobileRequestApp(){
 const [view,setView]=useState<View>("home"),[form,setForm]=useState(initial),[ots,setOts]=useState<any[]>([]),[problems,setProblems]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[q,setQ]=useState(""),[msg,setMsg]=useState(""),[photos,setPhotos]=useState<File[]>([]),[photo,setPhoto]=useState(""),[email,setEmail]=useState("");
 const nav=(v:View)=>{setView(v);setQ("");setMsg("");window.scrollTo({top:0,behavior:"smooth"})}; const update=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const load=async()=>{const [a,b,c,p]=await Promise.all([fetch("/api/ops-desk?type=cases").then(x=>x.json()),fetch("/api/ops-desk?type=problems").then(x=>x.json()),fetch("/api/ops-desk?type=requests").then(x=>x.json()),fetch("/api/ops-desk?type=profile").then(x=>x.json())]);setOts(a.items||[]);setProblems(b.items||[]);setRequests(c.items||[]);setEmail(p.profile?.email||"");if(p.profile?.photo_url)setPhoto(p.profile.photo_url)};
 useEffect(()=>{load().catch(()=>{});const t=window.setInterval(()=>load().catch(()=>{}),60000);return()=>clearInterval(t)},[]);
 const submit=async()=>{const problem=view==="problem";let r:Response;if(problem){const d=new FormData();d.append("action","problem");d.append("awb",form.awb);d.append("category",form.category);d.append("division",form.department);d.append("location",form.location);d.append("description",form.reason);photos.forEach(x=>d.append("photos",x));r=await fetch("/api/ops-desk",{method:"POST",body:d})}else r=await fetch("/api/ops-desk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"createRequest",...form})});const x=await r.json();setMsg(r.ok&&x.ok?(problem?"Problem berhasil dikirim.":"Request berhasil dikirim."):x.error||"Gagal menyimpan.");if(r.ok&&x.ok){load();if(!problem){setForm(initial);setView("home")}}};
 const status=(s:string)=>s==="resolved"||s==="closed"?"Selesai":s==="in_progress"||s==="verified"?"Diproses":"Diajukan"; const all=useMemo(()=>[...problems.map(x=>({...x,k:"problem",t:"Barang Problem",d:x.awb||x.category})),...requests.map(x=>({...x,k:"request",t:"Request Helpdesk",d:x.description||x.type}))].sort((a,b)=>+new Date(b.created_at||0)-+new Date(a.created_at||0)).slice(0,4),[problems,requests]);
 const list=(arr:any[],kind:string)=>arr.length?<div className="pwa-list">{arr.map((x,i)=><button className="pwa-list-item" key={x.id||x.awb||i}><span className={`pwa-list-icon ${kind}`}>{kind==="problem"?<Package/>:<Boxes/>}</span><span><strong>{x.awb||x.user_id||"Request"}</strong><small>{x.category||x.description||x.type||"Menunggu tindak lanjut"}</small><small>{x.created_at?new Date(x.created_at).toLocaleString("id-ID"):""}</small></span><em>{status(x.status||"open")}</em><ChevronRight/></button>)}</div>:<div className="pwa-empty">Belum ada data</div>;
 const formView=view==="problem"?<section className="mobile-card pwa-form"><label>Kategori problem<select value={form.category} onChange={e=>update("category",e.target.value)}><option>INVALID</option><option>UN SMU</option><option>BREACH 37</option><option>HOLD WH1</option><option>CRISCROSS</option><option>LAINNYA</option></select></label><label>Nomor AWB<input value={form.awb} onChange={e=>update("awb",e.target.value)} placeholder="Nomor AWB"/></label><div className="mobile-grid"><label>Divisi<input value={form.department} onChange={e=>update("department",e.target.value)}/></label><label>Lokasi<input value={form.location} onChange={e=>update("location",e.target.value)}/></label></div><label>Keterangan<textarea value={form.reason} onChange={e=>update("reason",e.target.value)} rows={5}/></label><label>Foto bukti<input type="file" accept="image/*" multiple onChange={e=>setPhotos(Array.from(e.target.files||[]))}/><small>{photos.length} foto dipilih</small></label><button className="mobile-submit" disabled={!form.awb||!form.reason} onClick={submit}>Kirim laporan</button>{msg&&<div className="mobile-message">{msg}</div>}</section>:<section className="mobile-card pwa-form"><label>Jenis request<select value={form.type} onChange={e=>update("type",e.target.value)}><option value="activation_user">Aktivasi User TGR</option><option value="open_cl3">Open CL3</option></select></label><label>Nama karyawan<input value={form.name} onChange={e=>update("name",e.target.value)}/></label><label>Keterangan<textarea value={form.reason} onChange={e=>update("reason",e.target.value)} rows={5}/></label><button className="mobile-submit" onClick={submit}>Kirim request</button>{msg&&<div className="mobile-message">{msg}</div>}</section>;
 const home=<><section className="pwa-activity-card"><h2>Aktivitas Hari Ini</h2><div className="pwa-activity-stats"><span><b>{problems.length+requests.length}</b><small>Laporan</small></span><span><b>{problems.filter(x=>x.status!=="resolved").length+requests.filter(x=>x.status==="pending").length}</b><small>Diproses</small></span><span><b>{problems.filter(x=>x.status==="resolved").length+requests.filter(x=>x.status==="resolved").length}</b><small>Selesai</small></span></div><div className="pwa-progress"><span style={{width:`${problems.length+requests.length?Math.min(100,problems.filter(x=>x.status==="resolved").length/(problems.length+requests.length)*100):0}%`}}/></div></section><section className="pwa-section"><h2>Layanan Operasional</h2><p>Pilih layanan untuk mulai</p><div className="pwa-service-grid"><button className="pwa-service problem" onClick={()=>nav("problem")}><Package/><strong>Barang Problem</strong><small>Laporkan kendala barang</small><ChevronRight/></button><button className="pwa-service helpdesk" onClick={()=>nav("helpdesk")}><Headphones/><strong>Request Helpdesk</strong><small>Ajukan bantuan tim</small><ChevronRight/></button></div><button className="pwa-service carry" onClick={()=>nav("activity")}><span><strong>Bawaan Kurir</strong><small>Catat barang bawaan kurir</small></span><span className="carry-art"><Package/><Boxes/></span><ChevronRight/></button><button className="pwa-all-services" onClick={()=>nav("activity")}><Grid2x2/>Lihat semua layanan<ChevronRight/></button></section><section className="pwa-section pwa-recent"><div className="pwa-section-head"><div><h2>Aktivitas Terbaru</h2><p>Riwayat laporan dan request tim</p></div><button onClick={()=>nav("problem")}>Lihat semua<ChevronRight/></button></div>{all.length?all.map((x,i)=><button className="pwa-recent-row" key={x.id||i}><span className={`recent-icon ${x.k}`}>{x.k==="problem"?<Package/>:<Headphones/>}</span><span><strong>{x.t}</strong><small>{x.d||"Aktivitas operasional"}</small></span><em className={status(x.status)==="Selesai"?"done":status(x.status)==="Diproses"?"progress":"submitted"}>{status(x.status)}</em><ChevronRight/></button>):<div className="pwa-empty">Belum ada aktivitas terbaru</div>}</section></>;
 const header=<header className="pwa-header"><div className="pwa-header-top"><div className="pwa-brand"><span className="pwa-logo">JNE</span><strong>OPS LEGUT</strong></div><div className="pwa-header-actions"><button aria-label="Notifikasi"><Bell/><i/></button><label className="mobile-avatar">{photo?<img src={photo} alt="Profil"/>:<b>OP</b>}<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setPhoto(URL.createObjectURL(f))}}/></label></div></div>{view==="home"&&<div className="pwa-welcome"><span>{greeting()} 👋</span><h1>Siap mulai operasional?</h1><p>Kelola laporan dan kebutuhan timmu</p></div>}</header>;
 return <main className="mobile-request">{header}{view==="home"?home:view==="activity"?<><div className="pwa-page-title">Riwayat Aktivitas</div><div className="pwa-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari AWB..."/></div>{list([...ots,...problems,...requests].filter(x=>String(x.awb||x.user_id||x.description||"").toLowerCase().includes(q.toLowerCase())),"ots")}</>:view==="problem"?<><div className="pwa-page-title">Data Problem</div>{formView}{list(problems,"problem")}</>:view==="helpdesk"?<><div className="pwa-page-title">Request Helpdesk</div>{formView}</>:view==="notifications"?<section className="pwa-empty pwa-notifications"><Bell/><strong>Belum ada notifikasi</strong><small>Notifikasi operasional akan muncul di sini.</small></section>:<section className="mobile-profile pwa-profile-page"><div className="profile-photo-large">{photo?<img src={photo} alt="Profil"/>:<b>OP</b>}</div><strong>{email||"Admin OPS"}</strong><small>Operator OPS LEGUT</small></section>}<nav className="mobile-nav"><button className={view==="home"?"active":""} onClick={()=>nav("home")}><Home/><small>Beranda</small></button><button className={view==="activity"?"active":""} onClick={()=>nav("activity")}><Boxes/><small>Riwayat</small></button><button className="pwa-camera-button" aria-label="Buat problem" onClick={()=>nav("problem")}><Camera/><small>Problem</small></button><button className={view==="notifications"?"active":""} onClick={()=>nav("notifications")}><Bell/><small>Notifikasi</small></button><button className={view==="profile"?"active":""} onClick={()=>nav("profile")}><UserRound/><small>Akun</small></button></nav></main>;
}
