"use client";
import { useEffect, useState } from "react";
import { Boxes, CheckCircle2, Clock, Search, Upload, Plus, Image as ImageIcon, X } from "lucide-react";
type Row = Record<string, any>;
async function api(type: string, q = "") { const r = await fetch(`/api/ops-desk?type=${type}&q=${encodeURIComponent(q)}`); return r.json(); }
const categories = ["INVALID", "UN SMU", "BREACH 37", "HOLD WH1", "CRISCROSS", "LAINNYA"];
export function OpsDeskView({ mode = "overview" }: { mode?: "overview" | "ots" | "problems" | "employees" | "users" }) {
  const [items, setItems] = useState<Row[]>([]), [summary, setSummary] = useState<Row>({}), [q, setQ] = useState(""), [paste, setPaste] = useState(""), [message, setMessage] = useState(""), [showProblem, setShowProblem] = useState(false), [division, setDivision] = useState("Semua divisi"), [form, setForm] = useState<Row>({ category: categories[0], division: "" }), [photos, setPhotos] = useState<File[]>([]), [userEmail, setUserEmail] = useState(""), [userRole, setUserRole] = useState("pending"), [leaderName, setLeaderName] = useState("");
  const type = mode === "overview" ? "overview" : mode === "ots" ? "cases" : mode;
  const load = async () => { const x = await api(type, q); setItems(x.items || []); if (mode === "overview") setSummary(x); };
  useEffect(() => { load(); }, [mode, q]);
  const importRows = async () => { const lines = paste.trim().split(/\r?\n/).map(x => x.split("\t")); const headers = lines.shift()!.map(x => x.trim().toLowerCase()); const rows = lines.filter(x => x[0]).map(x => Object.fromEntries(headers.map((h, i) => [h.replace(" ", "_"), x[i] || ""]))); const r = await fetch("/api/ops-desk", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "import", rows }) }); setMessage(r.ok ? `${rows.length} baris diproses` : "Impor gagal"); setPaste(""); load(); };
  const saveProblem = async () => { const data = new FormData(); data.append("action", "problem"); Object.entries(form).forEach(([key, value]) => data.append(key, String(value || ""))); photos.forEach(file => data.append("photos", file)); const r = await fetch("/api/ops-desk", { method: "POST", body: data }); setMessage(r.ok ? "Problem berhasil dicatat" : "Gagal menyimpan problem"); setShowProblem(false); setForm({ category: categories[0], division: "" }); setPhotos([]); load(); };
  const saveRole = async () => { const r = await fetch("/api/ops-desk", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "role", email: userEmail, role: userRole, leaderName }) }); setMessage(r.ok ? "Role administrasi disimpan" : "Gagal menyimpan role"); if (r.ok) { setUserEmail(""); setLeaderName(""); load(); } };
  const title = mode === "overview" ? "Ringkasan OPS Desk" : mode === "ots" ? "Monitoring OTS" : mode === "problems" ? "Problem barang" : mode === "employees" ? "Data Karyawan" : "Role Administrasi";
  const visibleProblems = division === "Semua divisi" ? items : items.filter(x => x.division === division);
  return <><div className="section-head"><div><div className="eyebrow">OPERASIONAL · TANGERANG SELATAN</div><h1 className="headline">{title}</h1><div className="subtitle">{mode === "problems" ? "Simpan dan telusuri problem barang dari setiap divisi admin." : "Fitur OTS, arsip problem, dan data tim dalam desain OPS LEGUT."}</div></div>{mode === "ots" && <button className="primary" onClick={() => document.getElementById("ots-import")?.scrollIntoView()}><Upload size={15}/> Impor OTS</button>}{mode === "problems" && <button className="primary" onClick={() => setShowProblem(true)}><Plus size={16}/> Catat problem</button>}</div>
  {mode === "overview" ? <><div className="kpi-grid"><div className="kpi"><Clock size={18}/><span>Outstanding OTS</span><strong>{items.filter(x => x.status === "open").length}</strong></div><div className="kpi"><CheckCircle2 size={18}/><span>Case closed</span><strong>{items.filter(x => x.status === "closed").length}</strong></div><div className="kpi"><Boxes size={18}/><span>Problem tercatat</span><strong>{summary.problems || 0}</strong></div></div><div className="card"><div className="card-head"><div className="card-title">Outstanding terbaru</div></div><Rows items={items.filter(x => x.status === "open").slice(0, 10)} /></div></> : mode === "problems" ? <><div className="toolbar"><div className="search"><Search size={16}/><input value={q} onChange={e => setQ(e.target.value)} placeholder="Cari AWB atau kategori" /></div><select value={division} onChange={e => setDivision(e.target.value)}><option>Semua divisi</option>{Array.from(new Set(items.map(x => x.division).filter(Boolean))).map(x => <option key={x}>{x}</option>)}</select><span>{visibleProblems.length} catatan</span></div><div className="problem-grid">{visibleProblems.map((x, i) => <div className="problem-card" key={x.id || i}><div className="problem-icon"><ImageIcon size={21}/></div><span className="category">{x.category || "LAINNYA"}</span><strong>{x.awb || "AWB belum dicatat"}</strong><small>{x.division || "Divisi belum dicatat"} · {x.location || "Lokasi belum dicatat"} · {x.created_at ? new Date(x.created_at).toLocaleDateString("id-ID") : "Tanggal belum dicatat"}</small><p>{x.description || "Tanpa keterangan"}</p></div>)}</div></> : <><div className="toolbar"><div className="search"><Search size={16}/><input value={q} onChange={e => setQ(e.target.value)} placeholder="Cari AWB, nama, NIK, kategori..." /></div><span>{items.length} data</span></div>{mode === "ots" && <div id="ots-import" className="card" style={{ padding: 16, marginBottom: 16 }}><div className="card-title">Impor dari Excel</div><p className="card-sub">Tempel tabel dengan header AWB, leader, zona, consignee, address, service, SLA.</p><textarea value={paste} onChange={e => setPaste(e.target.value)} placeholder="AWB\tLEADER\tZONE\nJT123\tAKBAR\tZONA A" style={{ width: "100%", minHeight: 90, margin: "10px 0" }}/><button className="primary" disabled={!paste.trim()} onClick={importRows}>Simpan data</button></div>}<div className="card"><Rows items={items}/></div></>}
  {showProblem && <div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={() => { setShowProblem(false); setPhotos([]); }}><X size={18}/></button><h2>Catat problem barang</h2><label>Nomor AWB<input value={form.awb || ""} onChange={e => setForm({...form, awb: e.target.value})} placeholder="Masukkan nomor resi" /></label><label>Divisi admin<select value={form.division} onChange={e => setForm({...form, division: e.target.value})}><option value="">Pilih divisi</option><option>Admin Inbound</option><option>Admin OTS</option><option>Admin Warehouse</option><option>Admin Delivery</option><option>Admin Customer Service</option></select></label><label>Kategori<select value={form.category} onChange={e => setForm({...form, category: e.target.value})}>{categories.map(x => <option key={x}>{x}</option>)}</select></label><label>Lokasi barang<input value={form.location || ""} onChange={e => setForm({...form, location: e.target.value})} placeholder="Contoh: Rak hold WH1" /></label><label>Keterangan<textarea value={form.description || ""} onChange={e => setForm({...form, description: e.target.value})} placeholder="Jelaskan kondisi/problem barang" /></label><label>Foto barang<input type="file" accept="image/*" capture="environment" multiple onChange={e => setPhotos(Array.from(e.target.files || []))} /><small>{photos.length ? `${photos.length} foto dipilih` : "Ambil foto dengan kamera HP atau pilih dari galeri"}</small></label>{photos.length > 0 && <div className="photo-preview">{photos.map(file => <img key={file.name + file.size} src={URL.createObjectURL(file)} alt={file.name} />)}</div>}<button className="primary full" disabled={!form.awb || !form.division} onClick={saveProblem}>Simpan problem</button></div></div>}
  {message && <div className="toast">{message}</div>}</>;
}
function Rows({ items }: { items: Row[] }) { return <div className="table-wrap"><table><thead><tr><th>AWB / Nama</th><th>Leader / Jabatan</th><th>Zona / Hub</th><th>Status</th></tr></thead><tbody>{items.map((x, i) => <tr key={x.id || x.nik || i}><td><strong>{x.awb || x.name || x.email || x.nik}</strong><small>{x.consignee || x.category || x.nik || x.description || ""}</small></td><td>{x.leader || x.position || x.role || "—"}</td><td>{x.zone || x.hub || x.location || x.leader_name || "—"}</td><td><span className="pill">{x.status || (x.active === false ? "Nonaktif" : "Aktif")}</span></td></tr>)}</tbody></table>{!items.length && <div className="empty"><Boxes size={25}/><strong>Belum ada data</strong></div>}</div>; }
